### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by johnpryan** [wal33d006/jumping_dots#2]

**Comment by wal33d006** [comment]
Add some description please.

**Comment by johnpryan** [comment]
In order for users to use, change and distribute software you need a software license: https://help.github.com/articles/licensing-a-repository/

thanks!

**Comment by wal33d006** [comment]
Thanks for this! I didn't know things about open source licensing. Will surely add one now.

**Comment by johnpryan** [comment]
ok, thanks!

**Comment by aubykhan** [comment]
I think it's a pretty good suggestion. I'll be adding it soon.
